name: Flutter CI

on:
  push:
    branches: [ github-actions-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'stable'
      - name: Building apk file
        run: echo $KEY_JKS > /home/runner/work/FlutterBMI/FlutterBMI/android/app/key.jsk && flutter pub get && flutter build apk
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}

